name: Check Flakiness
on:
  push:
    branches: ["main"]

jobs:
  Flaky_Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Playwright
        run: npx playwright install
      - name: Install dependencies
        run: npm ci --deps
      - name: Run Playwright
        run: npm run test
